In [1]:
from significance_analysis.tools import model,cd_diagram, model_builder
from significance_analysis.dataset_management import get_dataset,convert_to_autorank
from autorank import autorank, create_report

data_fig5 = get_dataset('fig5_full')
data_fig7 = get_dataset('fig7_full')

In [10]:
data_fig5["seed"]=data_fig5["seed"].astype(int)
data_fig5[["algorithm","benchmark","used_fidelity","value","normalized_regret","seed","prior"]].head(8)

  algorithm  benchmark  used_fidelity     value  normalized_regret  seed prior
0        PB  LC-167190       1.000000  0.521580           0.980631     0   bad
1        PB  LC-167190       1.019231  0.445254           0.784261     0   bad
2        PB  LC-167190       1.020000  0.445254           0.784261     0   bad
3        PB  LC-167190       1.027027  0.445254           0.784261     0   bad
4        PB  LC-167190       1.030303  0.445254           0.784261     0   bad
5        PB  LC-167190       1.035000  0.445254           0.784261     0   bad
6        PB  LC-167190       1.038462  0.445254           0.784261     0   bad
7        PB  LC-167190       1.054054  0.445254           0.784261     0   bad

In [5]:
data_fig5[["algorithm","normalized_regret"]].head(8)

  algorithm  normalized_regret
0        PB           0.980631
1        PB           0.784261
2        PB           0.784261
3        PB           0.784261
4        PB           0.784261
5        PB           0.784261
6        PB           0.784261
7        PB           0.784261

In [6]:
data_fig5[["algorithm","benchmark","normalized_regret"]].head(8)

  algorithm  benchmark  normalized_regret
0        PB  LC-167190           0.980631
1        PB  LC-167190           0.784261
2        PB  LC-167190           0.784261
3        PB  LC-167190           0.784261
4        PB  LC-167190           0.784261
5        PB  LC-167190           0.784261
6        PB  LC-167190           0.784261
7        PB  LC-167190           0.784261

In [11]:
data_fig5[["algorithm","benchmark","used_fidelity","normalized_regret","seed"]].head(8)

  algorithm  benchmark  used_fidelity  normalized_regret  seed
0        PB  LC-167190       1.000000           0.980631     0
1        PB  LC-167190       1.019231           0.784261     0
2        PB  LC-167190       1.020000           0.784261     0
3        PB  LC-167190       1.027027           0.784261     0
4        PB  LC-167190       1.030303           0.784261     0
5        PB  LC-167190       1.035000           0.784261     0
6        PB  LC-167190       1.038462           0.784261     0
7        PB  LC-167190       1.054054           0.784261     0

In [8]:
data_fig5[["algorithm","benchmark","used_fidelity","normalized_regret","prior"]].head(8)

  algorithm  benchmark  used_fidelity  normalized_regret prior
0        PB  LC-167190       1.000000           0.980631   bad
1        PB  LC-167190       1.019231           0.784261   bad
2        PB  LC-167190       1.020000           0.784261   bad
3        PB  LC-167190       1.027027           0.784261   bad
4        PB  LC-167190       1.030303           0.784261   bad
5        PB  LC-167190       1.035000           0.784261   bad
6        PB  LC-167190       1.038462           0.784261   bad
7        PB  LC-167190       1.054054           0.784261   bad